---
# Check that dockernet is setup
- name: setup dockernet
  docker_network:
    name: dockernet
    state: present

- name: pull the mongo docker image
  docker_image:
    name: mongo:4.2

- name: run the mongo docker image
  docker_container:
    name: mongo
    image: mongo:4.2
    networks:
    - name: "dockernet"
    ports: 
    - "27017:27017"
    hostname: "docker-mongo-server"
    detach: true
    state: started