- name: install docker.io and python3-docker
  apt:
    pkg:
    - docker.io
    - python3-docker
  become: yes

- name: add docker group
  group: 
    name: docker
    state: present
  become: yes

- name: add {{ user }} to docker group
  shell: usermod -aG docker {{ user }}
  become: yes

- name: setup dockernet
  docker_network:
    name: dockernet