---
- name: check for the image archive
  local_action: "stat path={{ playbook_dir }}/simple-http-service_v1_0.tar"
  register: path_exists
  failed_when: path_exists.stat.exists == false

- name: copy image archive to host
  copy: 
    src: "{{ playbook_dir }}/simple-http-service_v1_0.tar"
    dest: ./simple-http-service/simple-http-service_v1_0.tar

- name: load container from archive
  docker_image:
    name: simple-http-service:v1.0
    load_path: ./simple-http-service/simple-http-service_v1_0.tar
    state: present