---
- hosts: build_host
  gather_facts: no
  tasks:

  - name: create build directory
    file:
      path: ./simple-http-service
      state: directory
      mode: '0755'
  
  - name: copy app
    copy: 
      src: ../app
      dest: ./simple-http-service/
  
  - name: copy Dockerfile
    copy: 
      src: ../Dockerfile
      dest: ./simple-http-service/Dockerfile

  - name: copy requirements
    copy: 
      src: ../requirements.txt
      dest: ./simple-http-service/requirements.txt

  - name: build simple-http-service docker image
    docker_image:
      name: simple-http-service:v1.0
      build:
        path: ./simple-http-service
      state: present

  - name: save simple-http-service docker image
    docker_image:
      name: simple-http-service:v1.0
      archive_path: ./simple-http-service/simple-http-service_v1_0.tar
      state: present

  - name: fetch simple-http-service image archive
    fetch:
      src: ./simple-http-service/simple-http-service_v1_0.tar
      dest: ./simple-http-service_v1_0.tar
      flat: true